//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionAttemptHistory) DeepCopyInto(out *ActionAttemptHistory) {
	*out = *in
	in.TriggeredAt.DeepCopyInto(&out.TriggeredAt)
	if in.TailLogs != nil {
		in, out := &in.TailLogs, &out.TailLogs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionAttemptHistory.
func (in *ActionAttemptHistory) DeepCopy() *ActionAttemptHistory {
	if in == nil {
		return nil
	}
	out := new(ActionAttemptHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRecord) DeepCopyInto(out *ActionRecord) {
	*out = *in
	in.LastAttemptAt.DeepCopyInto(&out.LastAttemptAt)
	in.NextEligibleAt.DeepCopyInto(&out.NextEligibleAt)
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]ActionAttemptHistory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRecord.
func (in *ActionRecord) DeepCopy() *ActionRecord {
	if in == nil {
		return nil
	}
	out := new(ActionRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppClusterStateMap) DeepCopyInto(out *AppClusterStateMap) {
	*out = *in
	if in.ClusterStates != nil {
		in, out := &in.ClusterStates, &out.ClusterStates
		*out = make([]ClusterRevisionState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppClusterStateMap.
func (in *AppClusterStateMap) DeepCopy() *AppClusterStateMap {
	if in == nil {
		return nil
	}
	out := new(AppClusterStateMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeWindow) DeepCopyInto(out *ChangeWindow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeWindow.
func (in *ChangeWindow) DeepCopy() *ChangeWindow {
	if in == nil {
		return nil
	}
	out := new(ChangeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChangeWindow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeWindowList) DeepCopyInto(out *ChangeWindowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChangeWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeWindowList.
func (in *ChangeWindowList) DeepCopy() *ChangeWindowList {
	if in == nil {
		return nil
	}
	out := new(ChangeWindowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChangeWindowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeWindowSpec) DeepCopyInto(out *ChangeWindowSpec) {
	*out = *in
	if in.ImpactedApps != nil {
		in, out := &in.ImpactedApps, &out.ImpactedApps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.EndTime.DeepCopyInto(&out.EndTime)
	out.HardRefresh = in.HardRefresh
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeWindowSpec.
func (in *ChangeWindowSpec) DeepCopy() *ChangeWindowSpec {
	if in == nil {
		return nil
	}
	out := new(ChangeWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeWindowStatus) DeepCopyInto(out *ChangeWindowStatus) {
	*out = *in
	if in.SilentClusters != nil {
		in, out := &in.SilentClusters, &out.SilentClusters
		*out = make([]SilentClusterState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make(map[string]ActionRecord, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.Validation.DeepCopyInto(&out.Validation)
	in.LastReportedAt.DeepCopyInto(&out.LastReportedAt)
	if in.AppStates != nil {
		in, out := &in.AppStates, &out.AppStates
		*out = make(map[string]AppClusterStateMap, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeWindowStatus.
func (in *ChangeWindowStatus) DeepCopy() *ChangeWindowStatus {
	if in == nil {
		return nil
	}
	out := new(ChangeWindowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAppReport) DeepCopyInto(out *ClusterAppReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAppReport.
func (in *ClusterAppReport) DeepCopy() *ClusterAppReport {
	if in == nil {
		return nil
	}
	out := new(ClusterAppReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAppReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAppReportList) DeepCopyInto(out *ClusterAppReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterAppReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAppReportList.
func (in *ClusterAppReportList) DeepCopy() *ClusterAppReportList {
	if in == nil {
		return nil
	}
	out := new(ClusterAppReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAppReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAppReportSpec) DeepCopyInto(out *ClusterAppReportSpec) {
	*out = *in
	out.MCPStatus = in.MCPStatus
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAppReportSpec.
func (in *ClusterAppReportSpec) DeepCopy() *ClusterAppReportSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterAppReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRevisionState) DeepCopyInto(out *ClusterRevisionState) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	out.MCPStatus = in.MCPStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRevisionState.
func (in *ClusterRevisionState) DeepCopy() *ClusterRevisionState {
	if in == nil {
		return nil
	}
	out := new(ClusterRevisionState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardRefreshConfig) DeepCopyInto(out *HardRefreshConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardRefreshConfig.
func (in *HardRefreshConfig) DeepCopy() *HardRefreshConfig {
	if in == nil {
		return nil
	}
	out := new(HardRefreshConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigPoolStatus) DeepCopyInto(out *MachineConfigPoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigPoolStatus.
func (in *MachineConfigPoolStatus) DeepCopy() *MachineConfigPoolStatus {
	if in == nil {
		return nil
	}
	out := new(MachineConfigPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropagationStatus) DeepCopyInto(out *PropagationStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropagationStatus.
func (in *PropagationStatus) DeepCopy() *PropagationStatus {
	if in == nil {
		return nil
	}
	out := new(PropagationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PropagationStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropagationStatusList) DeepCopyInto(out *PropagationStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PropagationStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropagationStatusList.
func (in *PropagationStatusList) DeepCopy() *PropagationStatusList {
	if in == nil {
		return nil
	}
	out := new(PropagationStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PropagationStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropagationStatusSpec) DeepCopyInto(out *PropagationStatusSpec) {
	*out = *in
	if in.TargetClusters != nil {
		in, out := &in.TargetClusters, &out.TargetClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropagationStatusSpec.
func (in *PropagationStatusSpec) DeepCopy() *PropagationStatusSpec {
	if in == nil {
		return nil
	}
	out := new(PropagationStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropagationStatusStatus) DeepCopyInto(out *PropagationStatusStatus) {
	*out = *in
	if in.ClusterStates != nil {
		in, out := &in.ClusterStates, &out.ClusterStates
		*out = make([]ClusterRevisionState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ExpectedRevisionSince.DeepCopyInto(&out.ExpectedRevisionSince)
	if in.DivergedClusters != nil {
		in, out := &in.DivergedClusters, &out.DivergedClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LaggingClusters != nil {
		in, out := &in.LaggingClusters, &out.LaggingClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StaleClusters != nil {
		in, out := &in.StaleClusters, &out.StaleClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MissingClusters != nil {
		in, out := &in.MissingClusters, &out.MissingClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropagationStatusStatus.
func (in *PropagationStatusStatus) DeepCopy() *PropagationStatusStatus {
	if in == nil {
		return nil
	}
	out := new(PropagationStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SilentClusterState) DeepCopyInto(out *SilentClusterState) {
	*out = *in
	in.LastSeenAt.DeepCopyInto(&out.LastSeenAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SilentClusterState.
func (in *SilentClusterState) DeepCopy() *SilentClusterState {
	if in == nil {
		return nil
	}
	out := new(SilentClusterState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationResult) DeepCopyInto(out *ValidationResult) {
	*out = *in
	if in.IssuesFound != nil {
		in, out := &in.IssuesFound, &out.IssuesFound
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationResult.
func (in *ValidationResult) DeepCopy() *ValidationResult {
	if in == nil {
		return nil
	}
	out := new(ValidationResult)
	in.DeepCopyInto(out)
	return out
}
